### ISSUE TITLE
Training Time for iNaturalist'18

### ISSUE THREAD

**Issue by duggalrahul** [Megvii-Nanjing/BBN#8]
Hi,

Thanks for the nice work in this repo!

Could you share your GPU setup and the training time per epoch on iNaturalist'18?

Best,
Rahul

**Comment by ZhouBoyan** [comment]
We use four  NVIDIA 1080ti GPU cards in iNaturalist experiments and the CUDA nad CUDNN version is 9.0 and 7.1.3 respectively. 
With two batches of data sampled from dual samplers, our training time is more than the baseline experiments (26min v.s 15min). Some tricks could accelerate the training process such as :(1) early stop, because the best epoch of our BBN is usually not the final one, (2) concat the two batches of data, feed them into the shared network and then split them.
Hope that will be useful for you !

**Comment by Kouuh** [comment]
When I use BBN for other data sets, how do I determine the total number of epochs and LR_STEP
